### PR TITLE
Header component

### PR DESCRIPTION
**Pull request by alan-wu**
# Description

This series of commits add the header to the design system. Most codes are same as the one used on the sparc-app but due to the complexity of the header, some of the reactive elements are handled differently.

For example, the currentPath prop replace router path; "Router-link" or "Nuxt-link" can be passed into the linkComponent prop depending on the environment.

The list of header items and 'links can also be passed in as prop as well.

Some icons have been added for the header using the new svg function and it is working well.

The documentation for the header has also been updated.

## Type of change

_Delete those that don't apply._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

I have updated App.vue to include the header and it is running [here](https://mapcore-demo.org/staging/design-system/#/).
The new documentation can be found [here](https://mapcore-demo.org/docs/design-system/?path=/story/large-components-header--page).

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added unit tests that prove my fix is effective or that my feature works
- [x] I have pushed the final commit message using the [changelog format](https://github.com/nih-sparc/sparc-design-system-components/wiki/Generating-a-Changelog)

### CODE REVIEW

**Comment by alan-wu** [comment]
@cameronbaney Please take a look at this and let me know if this is ready to be merged in so I can add the changelog commit message as the final commit. Thanks a lot!!!

**Review by cameronbaney — COMMENTED** [review]
This looks great. Good solution for the reactive elements in the header. My only feedback is to rename the `Header` component to be a [multi-word component name](https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential) like `SparcHeader`. This is largely to avoid conflicts with any native elements, and `header` is one of these tags.

**Comment by alan-wu** [comment]
Thanks Cameron, I agree with that the name being too generic. I will fix that up.

**Comment by alan-wu** [comment]
Hi @cameronbaney I have renamed Header to SparcHeader, thanks so much for reviewing it.

**Review by cameronbaney — APPROVED** [review]

**Pull request merged**
